-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- REQUIREMENT 1: THE kernels TABLE
CREATE TABLE IF NOT EXISTS kernels (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    role_name TEXT NOT NULL UNIQUE,
    domain TEXT NOT NULL,
    source_material TEXT[],
    axioms JSONB,
    logic_gates JSONB,
    system_prompt TEXT,
    rpc_enabled BOOLEAN DEFAULT true,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- REQUIREMENT 2: THE kernel_logs TABLE
CREATE TABLE IF NOT EXISTS kernel_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kernel_id UUID REFERENCES kernels(id),
    user_input TEXT,
    logic_trace TEXT,
    output TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- RLS & POLICIES
ALTER TABLE kernels ENABLE ROW LEVEL SECURITY;
ALTER TABLE kernel_logs ENABLE ROW LEVEL SECURITY;

-- Allow full access for now (Development Mode)
CREATE POLICY "Allow full access to kernels" 
ON kernels FOR ALL 
USING (true) 
WITH CHECK (true);

CREATE POLICY "Allow full access to kernel_logs" 
ON kernel_logs FOR ALL 
USING (true) 
WITH CHECK (true);
